collector:
  _target_: src.data_collection.data_collector.DataCollector
  game: Pong
  num_samples: 100
  max_num_objects: 32
  # model: "SAM"
  model: "FastSAM-x"
  # model: "FastSAM-s"
  force_collect: False
