defaults:
 - feature_extractor: feature_extractor
 - data_loader: standard

debug: True
lr: 0.001
batch_size: 32
time_steps: 10
num_objects: 8
name: debug-training
game: Pong
model: SAM
predictor: transformer
num_iterations: 1000
ground_truth_masks: false

save_models: false