defaults:
 - feature_extractor: feature_extractor

debug: True
batch_size: 10
time_steps: 4
num_objects: 8
name: debug-training
game: Pong
predictor: transformer
num_iterations: 1000
ground_truth_masks: false

save_models: false
