name: Code Quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint $(git ls-files '*.py')
    - name: Analysing the code with mypy
      run: |
        pipenv run mypy $(git ls-files '*.py')
